import { NextRequest } from "next/server";
import * as XLSX from "xlsx";
import { prisma } from "@/lib/db/prisma";
import { getCurrentUser } from "@/lib/auth";
import { errorResponse, successResponse } from "@/lib/api/response";
const allowed = (role?: string) => role === "ADMIN" || role === "MENTOR";
const normalize = (row: Record<string, unknown>) => ({ question: String(row.Question ?? row.question ?? "").trim(), options: [row.Option1 ?? row.option1, row.Option2 ?? row.option2, row.Option3 ?? row.option3, row.Option4 ?? row.option4, row.Option5 ?? row.option5, row.Option6 ?? row.option6, row.Option7 ?? row.option7, row.Option8 ?? row.option8].map(String).map((v) => v.trim()).filter(Boolean) });
export async function GET() { const user = await getCurrentUser(); if (!user || !allowed(user.role)) return errorResponse("Coach access required", "FORBIDDEN", 403); const items = await prisma.questionLibraryItem.findMany({ orderBy: { updatedAt: "desc" }, include: { options: { orderBy: { order: "asc" } }, createdBy: { select: { name: true } } } }); return successResponse({ items }); }
export async function POST(req: NextRequest) { const user = await getCurrentUser(); if (!user || !allowed(user.role)) return errorResponse("Coach access required", "FORBIDDEN", 403); try { const body = await req.json(); const rows = Array.isArray(body.items) ? body.items : [body]; const items = rows.map(normalize).filter((v) => v.question && v.options.length >= 2 && v.options.length <= 8); if (!items.length) return errorResponse("Each question needs 2 to 8 choices", "INVALID_QUESTIONS", 400); await prisma.$transaction(items.map((item) => prisma.questionLibraryItem.create({ data: { question: item.question, createdById: user.id, options: { create: item.options.map((text, order) => ({ text, order })) } } }))); return successResponse({ count: items.length }, undefined, 201); } catch { return errorResponse("Unable to save questions", "QUESTION_SAVE_ERROR", 400); } }
export async function PUT(req: NextRequest) { const user = await getCurrentUser(); if (!user || !allowed(user.role)) return errorResponse("Coach access required", "FORBIDDEN", 403); const form = await req.formData(); const file = form.get("file"); if (!(file instanceof File)) return errorResponse("Choose a CSV or Excel file", "FILE_REQUIRED", 400); try { const book = XLSX.read(await file.arrayBuffer(), { type: "array" }); const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(book.Sheets[book.SheetNames[0]]); const items = rows.map(normalize).filter((v) => v.question && v.options.length >= 2 && v.options.length <= 8); if (!items.length) return errorResponse("Use columns Question, Option1, Option2 (up to Option8)", "INVALID_FILE", 400); await prisma.$transaction(items.map((item) => prisma.questionLibraryItem.create({ data: { question: item.question, createdById: user.id, options: { create: item.options.map((text, order) => ({ text, order })) } } }))); return successResponse({ count: items.length }, undefined, 201); } catch { return errorResponse("Could not read the uploaded file", "IMPORT_ERROR", 400); } }
