// @cms/shared - Shared types, constants, and validations for Mentor Connect CMS

// Constants & Enums
export {
  UserRole,
  UserStatus,
  MessageType,
  PollChartType,
  MemberRole,
  InviteCodeStatus,
  AuditAction,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  MAX_ATTACHMENT_SIZE_BYTES,
  MAX_ATTACHMENT_SIZE_MB,
  MAX_MESSAGE_LENGTH,
  WORD_CLOUD_MAX_WORD_LENGTH,
} from "./constants";
export type { Permission } from "./constants";

// Validation Schemas
export {
  loginSchema,
  menteeJoinSchema,
  forgotPasswordSchema,
  resetPasswordSchema,
  claimAccountSchema,
  updateProfileSchema,
  createMentorSchema,
  createGroupSchema,
  updateGroupSchema,
  joinGroupSchema,
  sendMessageSchema,
  editMessageSchema,
  createPollSchema,
  castVoteSchema,
  createOpenQuestionSchema,
  submitAnswerSchema,
  createWordCloudSchema,
  submitWordSchema,
  wordCloudControlSchema,
  searchSchema,
  paginationSchema,
} from "./validations";

// Inferred Types from Schemas
export type {
  LoginInput,
  MenteeJoinInput,
  ForgotPasswordInput,
  ResetPasswordInput,
  ClaimAccountInput,
  UpdateProfileInput,
  CreateMentorInput,
  CreateGroupInput,
  UpdateGroupInput,
  JoinGroupInput,
  SendMessageInput,
  EditMessageInput,
  CreatePollInput,
  CastVoteInput,
  CreateOpenQuestionInput,
  SubmitAnswerInput,
  CreateWordCloudInput,
  SubmitWordInput,
  WordCloudControlInput,
  SearchInput,
  PaginationInput,
} from "./validations";

// Domain Types
export type {
  ApiResponse,
  ApiError,
  PaginationMeta,
  AuthTokens,
  AuthUser,
  JwtPayload,
  User,
  UserSummary,
  Group,
  GroupDetail,
  GroupSummary,
  GroupMember,
  Message,
  MessageEdit,
  InviteCode,
  Notification,
  NotificationType,
  AdminDashboardStats,
  MentorDashboardStats,
  MenteeDashboardStats,
  ActivityItem,
  ChartDataPoint,
  SocketEvents,
  SearchResults,
} from "./types";
